### ISSUE TITLE
No spacing between buttons with long text

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/website#111]
When button text gets too long and two buttons on line get wrapped, there is no spacing between them:

![Screenshot_2019-10-11 تبرع لِـ Weblate](https://user-images.githubusercontent.com/212189/66681934-138ed500-ec74-11e9-9086-70ee2907c746.png)

Can be seen on https://weblate.org/ar/donate/

**Comment by kamransarwar** [comment]
![image](https://user-images.githubusercontent.com/5537822/67377972-ee696300-f59f-11e9-939e-8f05389b8bfe.png)

I've fixed the CSS issue and generated the pull request. Please review.

**Comment by nijel** [comment]
Hmm, I don't see the pull request, maybe you forgot to create it?

**Comment by kamransarwar** [comment]
Sorry, I forgot to make pull request. I made it right now. Please review.

![image](https://user-images.githubusercontent.com/5537822/67391211-a8b89480-f5b7-11e9-91a0-a60e185cff13.png)
